name: Build and deploy Python app to Azure Web App - automation-spn-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r my-automation/requirements.txt  # ✅ Adjust if your file is inside a subfolder

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "__pycache__/*" ".git/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1EA2D3C6F5704E9E830B406C791A427C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_652C240CBF914187944E57ED26F19DF6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DA72A7ED683948388611B341B81128A7 }}

      - name: ⏱️ Wait before deploying (avoid SCM container race condition)
        run: sleep 30

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'automation-spn-server'
          slot-name: 'Production'
